In [40]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [41]:
from sFLD import *
from calculate_error import *

# Get the Files Containing the Simulated Spectral Data

In [42]:
e_pathname = "/Users/jameswallace/Desktop/Project/data/verification_run_2021-06-14-1239/Esun.csv"
l_pathname = "/Users/jameswallace/Desktop/Project/data/verification_run_2021-06-14-1239/Lo_spectrum_inclF.csv"
f_pathname = "/Users/jameswallace/Desktop/Project/data/verification_run_2021-06-14-1239/fluorescence_scalars.csv"

In [43]:
# place the spectra in readable dataframes
e_df = get_simulated_spectral_df(e_pathname)
l_df = get_simulated_spectral_df(l_pathname)
f_df = pd.read_csv(f_pathname)
f_df = f_df.iloc[1:]

In [44]:
f_df

,F_1stpeak,wl_1stpeak,F_2ndpeak,wl_2ndpeak,F684,F761,LFtot,EFtot,EFtot_RC
1,2.580042e-01,688,9.838331e-01,743,2.384629e-01,6.260723e-01,6.224326e-02,1.716320e-01,9.732947e-01
2,2.905716e-01,688,1.782283e+00,745,2.691920e-01,1.218111e+00,1.041191e-01,3.580515e-01,2.048691e+00
3,NaN,NaN,4.588023e-02,744,6.971679e-03,3.060413e-02,2.753618e-03,9.969291e-03,6.000935e-02
4,1.815786e-01,688,7.712303e-01,744,1.672150e-01,5.039461e-01,4.798758e-02,1.471511e-01,8.365975e-01
5,NaN,NaN,1.934167e+00,743,3.265757e-01,1.209673e+00,1.181830e-01,4.020510e-01,1.972992e+00
...,...,...,...,...,...,...,...,...,...
96,5.058635e-01,688,1.927562e+00,743,4.705572e-01,1.242862e+00,1.221072e-01,3.948080e-01,2.606323e+00
97,9.209527e-02,688,4.024141e-01,743,8.399391e-02,2.627766e-01,2.496619e-02,9.470071e-02,5.961596e-01
98,NaN,NaN,5.652094e-01,741,2.034614e-01,3.312547e-01,3.951280e-02,1.342318e-01,5.291807e-01
99,9.061376e-02,691,1.862221e-01,741,7.616846e-02,1.063879e-01,1.333588e-02,4.202215e-02,1.415487e-01
100,1.861814e-01,688,6.453736e-01,743,1.737390e-01,4.152898e-01,4.105086e-02,1.378910e-01,7.855934e-01

In [45]:
# now average them for every ten rows

e_average = average_dataframe(e_df, 10)
l_average = average_dataframe(l_df, 10)
f_average = average_dataframe(f_df, 10)

NameError: name 'e_spectra_df' is not defined